// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }




@import "tailwindcss";

:root {
  --background: #05070d;
  --foreground: #e8eaf0;
  --accent: #fbbf24;
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --font-sans: var(--font-geist-sans);
  --font-mono: var(--font-geist-mono);
}

* {
  scroll-behavior: smooth;
}

html {
  background: var(--background);
}

body {
  background: var(--background);
  color: var(--foreground);
  font-family: Arial, Helvetica, sans-serif;
  overflow-x: hidden;
}

/* ---------- Custom scrollbar ---------- */
::-webkit-scrollbar {
  width: 10px;
}
::-webkit-scrollbar-track {
  background: #05070d;
}
::-webkit-scrollbar-thumb {
  background: linear-gradient(180deg, rgba(251, 191, 36, 0.35), rgba(251, 191, 36, 0.15));
  border-radius: 999px;
  border: 2px solid #05070d;
}
::-webkit-scrollbar-thumb:hover {
  background: rgba(251, 191, 36, 0.5);
}
html {
  scrollbar-color: rgba(251, 191, 36, 0.3) #05070d;
  scrollbar-width: thin;
}

/* ---------- Film grain / atmosphere overlay ---------- */
.grain-overlay {
  position: fixed;
  inset: 0;
  z-index: 60;
  pointer-events: none;
  opacity: 0.05;
  mix-blend-mode: overlay;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='120' height='120'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");
}

/* Vignette to deepen the corners, matched to the site's near-black */
.vignette-overlay {
  position: fixed;
  inset: 0;
  z-index: 1;
  pointer-events: none;
  background: radial-gradient(ellipse 80% 60% at 50% 0%, transparent 40%, rgba(5, 7, 13, 0.6) 100%);
}

/* ---------- Scroll progress bar ---------- */
.scroll-progress {
  position: fixed;
  top: 0;
  left: 0;
  height: 2px;
  background: linear-gradient(90deg, #fbbf24, #f59e0b);
  z-index: 100;
  transform-origin: left;
  box-shadow: 0 0 8px rgba(251, 191, 36, 0.6);
}

/* ---------- Reveal-on-scroll ---------- */
.reveal {
  opacity: 0;
  transform: translateY(28px);
  transition: opacity 0.9s cubic-bezier(0.16, 1, 0.3, 1),
    transform 0.9s cubic-bezier(0.16, 1, 0.3, 1);
  transition-delay: var(--reveal-delay, 0ms);
  will-change: opacity, transform;
}
.reveal-visible {
  opacity: 1;
  transform: translateY(0);
}

.reveal-scale {
  opacity: 0;
  transform: scale(0.94);
  transition: opacity 1s cubic-bezier(0.16, 1, 0.3, 1),
    transform 1s cubic-bezier(0.16, 1, 0.3, 1);
  transition-delay: var(--reveal-delay, 0ms);
}
.reveal-scale.reveal-visible {
  opacity: 1;
  transform: scale(1);
}

.reveal-line {
  transform: scaleY(0);
  transform-origin: top;
  transition: transform 1.1s cubic-bezier(0.16, 1, 0.3, 1);
  transition-delay: var(--reveal-delay, 0ms);
}
.reveal-line.reveal-visible {
  transform: scaleY(1);
}

/* ---------- Ambient hero glow drift ---------- */
@keyframes drift {
  0%, 100% { transform: translate(0, 0); }
  50% { transform: translate(2%, -3%); }
}
.ambient-glow {
  animation: drift 14s ease-in-out infinite;
}

/* ---------- Subtle pulse for status dots ---------- */
@keyframes pulse-glow {
  0%, 100% { opacity: 1; box-shadow: 0 0 0 0 rgba(251, 191, 36, 0.5); }
  50% { opacity: 0.6; box-shadow: 0 0 0 4px rgba(251, 191, 36, 0); }
}
.pulse-dot {
  animation: pulse-glow 2.4s ease-in-out infinite;
}

/* ---------- Focus visibility (accessibility floor) ---------- */
a:focus-visible,
button:focus-visible {
  outline: 2px solid #fbbf24;
  outline-offset: 3px;
  border-radius: 2px;
}

/* ---------- Reduced motion ---------- */
@media (prefers-reduced-motion: reduce) {
  * {
    scroll-behavior: auto !important;
  }
  .reveal,
  .reveal-scale,
  .reveal-line {
    opacity: 1 !important;
    transform: none !important;
    transition: none !important;
  }
  .ambient-glow,
  .pulse-dot {
    animation: none !important;
  }
}
